### ISSUE TITLE
Error ao instalar

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/vue-brazil#10]
Criado por:
@samirissa00 

Depois de instalar com sucesso via npm no projeto
dá um erro de compilação !!

Failed to compile.
```
./node_modules/vue-brazil/src/index.js
Module not found: Error: [CaseSensitivePathsPlugin] c:\Users\samir\Dropbox\Vue_projects\vue-material-dashboard-pro-v1.3.2\node_modules\vue-brazil\src\filter\JSBrazilFilter.js does not match the corresponding path on disk JsBrazilFilter.js.
```

Referencia:
https://github.com/mariohmol/js-brasil/issues/48

**Comment by mariohmol** [comment]
@Ofamosomario

**Comment by samirissa00** [comment]
Ola, 

no projeto do Vue nos arquivos não existe este que dá erro "JSBrazilFilter.js" está faltando não sei se é necessário , mas o erro indica que um arquivo nao existe em determinado lugar !

e realmente nos arquivos do vue-brasil nao existem !!

**Comment by mariohmol** [comment]
Achei o bug... era problema de nome de arquivo com minu/maiusculo.. provavel q o role com window.. como uso mac nao estava dando erro..
subi na versao 0.0.3  se puder retestar? =)

se puder colaborar com outras features.. seria demais!!

obrigado

**Comment by samirissa00** [comment]
Instalação Ok ! 

λ npm install --save vue-brazil js-brasil
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ js-brasil@2.1.0
+ vue-brazil@0.0.3
added 6 packages from 4 contributors and audited 25965 packages in 17.437s

++++++++++++++++++++++++++++++++

Testando a utilização onde dava erro !

Compilou com sucessso !!

=================================

 DONE  Compiled successfully in 3431ms                                                                         11:01:02


  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.118:8080/
==================================

Utilização Ok !

{{ cpf | vueBrazil("cpf") }} 

Retorno na TELA   123.456.789-01

data() {
    return {
      cpf: "12345678901",
    }
}

Ok esto tudo redondo agora ! 

Sobre ajudar depois que acabar meu projeto consigo colaborar com algumas coisas, 
por onde acha que seria interessante no momento ?

**Comment by mariohmol** [comment]
Boa!!

Obrigado pelo interesse em colaborar..

um bom começo é fazer o Demo
https://github.com/mariohmol/vue-brazil/issues/9

Coisas que ainda nao sei resolver, é como seria o um validator em Vue?
Algo como no Form , se o cara colocar o input CPF errado ele mostrar uma mensagem ou dar um feedback ao submit do form.. nao sei como funciona o validate no Vue
https://github.com/mariohmol/vue-brazil/issues/8

Outro que da pra trabalhar é o Mask, como o Vue trabalhar pra criar um component que cria mask no input?
https://github.com/mariohmol/vue-brazil/issues/7
