### ISSUE TITLE
Erro ao validar e formatar CPF quando passa os valores numéricos.

### ISSUE THREAD

**Issue by douglas1983** [mariohmol/vue-brazil#11]
Se passar o CPF como valores númericos e não string retorna um erro: rawValue.split is not a function

Seria interessante converte automaticamente esses valores para string para não ter esse problema.

obs: Não testei as outras funções de formatação e validação.

**Comment by mariohmol** [comment]
valew!! 

subi uma versao nova com esse fix.

se puder ajudar a montar outras coisas tipo o Mask e o validator.. não sou expert em vuejs,fiz esse modulo mais pro https://github.com/mariohmol/js-brasil/

**Comment by mariohmol** [comment]
acabei fazendo o de mask aq.. ve se ficou bom #7
