### ISSUE TITLE
Mask

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/vue-brazil#7]
Criar uma diretiva como por exemplo:
https://github.com/probil/v-mask

Exemplo:
```vuejs
import { VueMaskDirective } from 'v-mask'
Vue.directive('mask', VueMaskDirective);
And in your component:

<v-text-field
  v-model="loginItem.phone"
  v-mask="'(###) ###-####'"
></v-text-field>
```

No caso do angular ele funciona da seguinte forma:
`<input type="text" formControlName="cnpj" cnpj [textMask]="{mask: MASKS.cnpj.textMask}">`

NO React funciona da seguinte forma:
`        <BrazilMaskComponent value="12345678900" format="cpf"/>`

Referencias 
* https://github.com/mariohmol/ng-brazil
* https://github.com/mariohmol/react-brazil

**Comment by douglas1983** [comment]
se tivesse um tipo getMask('cpf') e ele retorna-se a mascara '###.###.###-##' seria muito bom. 
Que ficaria tudo vinculado. Como uso Quasar os componentes dele tem uma diretiva mask pronta onde preciso só informar a mascara.

Com isso poderia usar no seu exemplo dessa maneira
```
<v-text-field
  v-model="loginItem.phone"
  :v-mask="getMask('cpf')"
></v-text-field>
```

**Comment by mariohmol** [comment]
tem q ver como é o formato dessa mascara q ele usa, as mascaras do JS brasil ficam aqui

https://github.com/mariohmol/js-brasil/blob/master/src/mask.ts

Acabei de criei a diretiva dessa forma `<input v-brazilmask="{ type: 'cpf' }" />`
